### ISSUE TITLE
Plugin cannot be installed on windows

### ISSUE THREAD

**Issue by Argelbargel** [Noksa/helm-resolve-deps#5]
Hi there,

i'd like to use your plugin on windows but it cannot be installed because

- it requires sh (i think a windows-powershell-script and a platformHook would be required: https://github.com/helm/helm/issues/7117)
- even when run via e.g. git bash/mingw the script fails as there seems to be no release-package for windows (for 2.0.0 this seems to be expected at https://github.com/Noksa/helm-resolve-deps/releases/download/v2.0.0/resolve-deps_2.0.0_windows_amd64.tar.gz).

Kind regards!

**Comment by Noksa** [comment]
@Argelbargel 
Thanks for your ticket!

I've tried to add support for windows. You can try to install it now.

**Comment by Argelbargel** [comment]
Hi @Noksa,

great, installation now works when running it in git bash!

Thank you and kind regards!

Argelbargel
